swagger: '2.0'
info:
  description: swab Online
  version: 1.0.0
  title: swab Online
  contact:
    email: ahmadshobirin.dev@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
- name: Auth
  description: Authentication Api

paths:
  /login:
    post:
      tags:
      - Auth
      summary: login users
      description: |
        Passing Username And Password to get Token JWT
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Login User
        description: Login User
        schema:
          $ref: '#/definitions/Login'
      responses:
        200:
          description: Response Auth Login
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                $ref: '#/definitions/JWT'
        400:
          description: invalid input, object invalid
  /register:
    post:
      tags:
      - Auth
      summary: Register users
      description: |
        send some data
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Register User
        description: Register User
        schema:
          type: object
          required:
          - name
          - email
          - password
          properties:
            name:
              type: string
              example: Ahmad Shobirin
            email:
              type: string
              format: email
              example: ahmadshobirin@alterra.com
            password:
              type: string
              example: k!UUdja21Sxh
            date_of_birth:
              type: string
              format: date
              example: 1999-01-01
      responses:
        200:
          description: Response Auth Login
          schema:
            type: object
            properties:
              status_code:
                type: integer
                example: 200
              message:
                type: string
                example: 'OK'
              data:
                $ref: '#/definitions/JWT'
        400:
          description: Bad Request

definitions:
  Login:
    type: object
    required:
    - email
    - password
    properties:
      email:
        type: string
        example: jhon@doe@gmail.com
      password:
        type: string
        example: QwanjjaseuQeq
        description: encrypted password AES
  JWT:
    type: object
    required:
    - token
    - expire_token
    - refresh_token
    - expire_refresh_token
    properties:
      email:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.|eyJleHAiOjE2Mjg1MTA1NzcsImp0aSI6ImV5SmhiR2NpT2l a7C6ZcazsgjdKXR2eXOPRzBhRv99NOaDMNN2gyYDE2Y
      expire_token:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
      refresh_token:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.|eyJleHAiOjE2Mjg1MTA1NzcsImp0aSI6ImV5SmhiR2NpT2l a7C6ZcazsgjdKXR2eXOPRzBhRv99NOaDMNN2gyYDE2Y
      expire_refresh_token:
        type: string
        example: 2021-08-09T12:02:57Z
        format: date-time
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /ahmadshobirin/swab-online
schemes:
 - https